flowchart LR
    subgraph Login
    Register(Register)
    OTP(OTP)
    end

    subgraph IssueCertificate
    Term(Term)
    Register2(Register)
    OTP2(OTP)
    Farashenasa(Farashenasa)
    Payment(Payment)
    Issue(Issue)
    end

    subgraph RevokeCertificate
    OTP3(OTP)
    end

    Dashboard(fa:fa-house Dashboard)
    SignPDF(SignPDF)
    Activities(Activities)
    Profile(Profile)
    Certificates(Certificates)
    CertificateInfo(CertificateInfo)

    Start((''))
    End((''))

    Start --> Register
    Register --> OTP
    OTP -- fa:fa-ban --> Dashboard

    Start --> Dashboard

    Dashboard --> Term
    Term -- fa:fa-ban --> Register2
    Register2 -- fa:fa-ban --> OTP2
    OTP2 -- fa:fa-ban --> Farashenasa
    Farashenasa -- fa:fa-ban --> Payment
    Payment -- fa:fa-ban --> Issue
    Issue -- fa:fa-ban --> Dashboard
    Issue --> End

    Dashboard --> SignPDF
    Dashboard --> Activities

    Dashboard -.- Profile
    Profile -- fa:fa-ban --> Register

    Dashboard -.- Certificates
    Certificates --> CertificateInfo
    CertificateInfo --> OTP3
    OTP3 -- fa:fa-ban --> Certificates

    classDef start_des stroke:#28e059;
    classDef end_des stroke:#de2333;
    classDef optional stroke:#ffffff,stroke-dasharray: 5 4;

    class Start start_des;
    class End end_des;
    class Term,Register,Register2,OTP2,Farashenasa,Payment optional;
